/*** Module Ra_Transmit, written by TTX-Mwcodegenerator (Version 0.17.0,   ***/
/*** 18-Apr-2018)/Remote_Access (Version 6.3.7, 11-Dec-2019)               ***/
/*** IFSet version: 1.1.20                                                 ***/

/** \file Ra_Transmit.h */

/* double include prevention */
#ifndef RA_TRANSMIT_H
#define RA_TRANSMIT_H

#ifdef __cplusplus
extern "C"
{
#endif /* __cplusplus */


#include "Rte_Type.h"
#include "Ra.h"
#define Ra_Transmit_CtApApa_FreeRunning_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApBISTASIL_SH00_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApBISTQM_SH00_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApComASILB_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApComASILD_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApComQM_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApDR_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApDSC_PH00_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApDiagnosticManager_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApE2ETranASILB_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApE2ETranASILD_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApFreeSpaceFusion_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApHighFrequencyPositioning_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApHostSupervisionMaster_SH00_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApImageProcess_FreeRunning_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApInertialProcess_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApIntegratedPositioning_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApInteractionProcess_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApLaneFusion_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApLocBuffer_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApMeProcess_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApMiddleMapmatching_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApMiddlewareASIL_PH00_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApMiddlewareASIL_SH00_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApMirrorDataManager_FreeRunning_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApMwrProcess_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApObstacleFusion_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApParkingLot_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApPathPlanner_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApPer_PH00_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApPer_SH00_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApPrediction_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApSOMEIPGW_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApStateMonitor_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApSysManager_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApTrafficElementFusion_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApTransformer_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApUSBCom_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtApUltrasonicHandler_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtCdDebug_PH00_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtCdDebug_SH00_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtCdErrorHandlerMaster_SH00_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtCdEyeQCom_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtCdLCSM_SH00_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtCdLCSS_PH00_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
#define Ra_Transmit_CtCdTimeMonitor_SH00_PpDiagCoding Ra_Transmit_CtApDSC_SH00_PpDiagCoding
void Ra_Transmit_CtApDSC_SH00_PpDiagCoding (Dt_RECORD_Diag_Coding * tDeCoding);
  
#define Ra_Transmit_CtApApa_FreeRunning_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApBISTASIL_PH00_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApBISTASIL_SH00_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApBISTQM_PH00_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApBISTQM_SH00_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApComASILB_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApComASILD_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApComQM_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApDR_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApDSC_PH00_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApDiagnosticManager_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApE2ETranASILB_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApE2ETranASILD_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApFreeSpaceFusion_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApHighFrequencyPositioning_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApHostSupervisionMaster_SH00_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApHostSupervisionSlave_PH00_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApImageProcess_FreeRunning_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApInertialProcess_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApIntegratedPositioning_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApInteractionProcess_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApLaneFusion_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApLocBuffer_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApMeProcess_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApMiddleMapmatching_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApMiddlewareASIL_PH00_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApMiddlewareASIL_SH00_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApMirrorDataManager_FreeRunning_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApMwrProcess_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApObstacleFusion_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApParkingLot_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApPathPlanner_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApPer_PH00_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApPer_SH00_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApPrediction_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApSOMEIPGW_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApStateMonitor_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApStbMASIL_PH00_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApStbMASIL_SH00_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApSysManager_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApTrafficElementFusion_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApTransformer_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApUSBCom_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtApUltrasonicHandler_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtCdDebug_PH00_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtCdDebug_SH00_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtCdErrorHandlerMaster_SH00_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtCdErrorHandlerProxy_PH00_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtCdEyeQCom_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtCdLCSM_SH00_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtCdLCSS_PH00_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtCdTimeMonitor_PH00_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
#define Ra_Transmit_CtCdTimeMonitor_SH00_PpDiagGlobalRead Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead
void Ra_Transmit_CtApDSC_SH00_PpDiagGlobalRead (Dt_BOOL * tDeFSPCleared);
  
#define Ra_Transmit_CtApFreeSpaceFusion_PpImageProcess_SVCameraFail_60ms Ra_Transmit_CtApImageProcess_FreeRunning_PpImageProcess_SVCameraFail_60ms
#define Ra_Transmit_CtApLaneFusion_PpImageProcess_SVCameraFail_60ms Ra_Transmit_CtApImageProcess_FreeRunning_PpImageProcess_SVCameraFail_60ms
#define Ra_Transmit_CtApLocBuffer_PpImageProcess_SVCameraFail_60ms Ra_Transmit_CtApImageProcess_FreeRunning_PpImageProcess_SVCameraFail_60ms
#define Ra_Transmit_CtApObstacleFusion_PpImageProcess_SVCameraFail_60ms Ra_Transmit_CtApImageProcess_FreeRunning_PpImageProcess_SVCameraFail_60ms
#define Ra_Transmit_CtApParkingLot_PpImageProcess_SVCameraFail_60ms Ra_Transmit_CtApImageProcess_FreeRunning_PpImageProcess_SVCameraFail_60ms
#define Ra_Transmit_CtApUSBCom_PpImageProcess_SVCameraFail_60ms Ra_Transmit_CtApImageProcess_FreeRunning_PpImageProcess_SVCameraFail_60ms
void Ra_Transmit_CtApImageProcess_FreeRunning_PpImageProcess_SVCameraFail_60ms (Dt_RECORD_SVCameraFail * tDeSurroundCameraFail);
  
#define Ra_Transmit_CtApUSBCom_PpInteractionProcess_USBCom_100ms Ra_Transmit_CtApInteractionProcess_PpInteractionProcess_USBCom_100ms
void Ra_Transmit_CtApInteractionProcess_PpInteractionProcess_USBCom_100ms
    ( Dt_RECORD_AIPilotObjsDsp * tDeAIPilotObjsDsp
    , Dt_RECORD_IECUNavigationInfo * tDeIECUNavigationInfo
    , Dt_RECORD_ParkingSpacesDsp * tDeParkingSpacesDsp
    );
  
#define Ra_Transmit_CtApDiagnosticManager_PpEthernetCom_AVCameraFail_100ms Ra_Transmit_CtApSOMEIPGW_PpEthernetCom_AVCameraFail_100ms
#define Ra_Transmit_CtApObstacleFusion_PpEthernetCom_AVCameraFail_100ms Ra_Transmit_CtApSOMEIPGW_PpEthernetCom_AVCameraFail_100ms
#define Ra_Transmit_CtApTrafficElementFusion_PpEthernetCom_AVCameraFail_100ms Ra_Transmit_CtApSOMEIPGW_PpEthernetCom_AVCameraFail_100ms
#define Ra_Transmit_CtApUSBCom_PpEthernetCom_AVCameraFail_100ms Ra_Transmit_CtApSOMEIPGW_PpEthernetCom_AVCameraFail_100ms
void Ra_Transmit_CtApSOMEIPGW_PpEthernetCom_AVCameraFail_100ms (Dt_RECORD_AVCameraFail * tDeAVCameraFail);
  
#define Ra_Transmit_CtApUSBCom_PpSysManager2USBCom_100ms Ra_Transmit_CtApSysManager_PpSysManager2USBCom_100ms
void Ra_Transmit_CtApSysManager_PpSysManager2USBCom_100ms (Dt_RECORD_SysManager2USBCom * tDeSysManager2USBCom);
  
#define Ra_Transmit_CtApDR_PpSysManager_DrivingModeSts_50ms Ra_Transmit_CtApSysManager_PpSysManager_DrivingModeSts_50ms
#define Ra_Transmit_CtApDiagnosticManager_PpSysManager_DrivingModeSts_50ms Ra_Transmit_CtApSysManager_PpSysManager_DrivingModeSts_50ms
#define Ra_Transmit_CtApFreeSpaceFusion_PpSysManager_DrivingModeSts_50ms Ra_Transmit_CtApSysManager_PpSysManager_DrivingModeSts_50ms
#define Ra_Transmit_CtApHighFrequencyPositioning_PpSysManager_DrivingModeSts_50ms Ra_Transmit_CtApSysManager_PpSysManager_DrivingModeSts_50ms
#define Ra_Transmit_CtApImageProcess_FreeRunning_PpSysManager_DrivingModeSts_50ms Ra_Transmit_CtApSysManager_PpSysManager_DrivingModeSts_50ms
#define Ra_Transmit_CtApInertialProcess_PpSysManager_DrivingModeSts_50ms Ra_Transmit_CtApSysManager_PpSysManager_DrivingModeSts_50ms
#define Ra_Transmit_CtApIntegratedPositioning_PpSysManager_DrivingModeSts_50ms Ra_Transmit_CtApSysManager_PpSysManager_DrivingModeSts_50ms
#define Ra_Transmit_CtApInteractionProcess_PpSysManager_DrivingModeSts_50ms Ra_Transmit_CtApSysManager_PpSysManager_DrivingModeSts_50ms
#define Ra_Transmit_CtApLaneFusion_PpSysManager_DrivingModeSts_50ms Ra_Transmit_CtApSysManager_PpSysManager_DrivingModeSts_50ms
#define Ra_Transmit_CtApLocBuffer_PpSysManager_DrivingModeSts_50ms Ra_Transmit_CtApSysManager_PpSysManager_DrivingModeSts_50ms
#define Ra_Transmit_CtApMeProcess_PpSysManager_DrivingModeSts_50ms Ra_Transmit_CtApSysManager_PpSysManager_DrivingModeSts_50ms
#define Ra_Transmit_CtApMiddleMapmatching_PpSysManager_DrivingModeSts_50ms Ra_Transmit_CtApSysManager_PpSysManager_DrivingModeSts_50ms
#define Ra_Transmit_CtApMirrorDataManager_FreeRunning_PpSysManager_DrivingModeSts_50ms Ra_Transmit_CtApSysManager_PpSysManager_DrivingModeSts_50ms
#define Ra_Transmit_CtApMwrProcess_PpSysManager_DrivingModeSts_50ms Ra_Transmit_CtApSysManager_PpSysManager_DrivingModeSts_50ms
#define Ra_Transmit_CtApObstacleFusion_PpSysManager_DrivingModeSts_50ms Ra_Transmit_CtApSysManager_PpSysManager_DrivingModeSts_50ms
#define Ra_Transmit_CtApParkingLot_PpSysManager_DrivingModeSts_50ms Ra_Transmit_CtApSysManager_PpSysManager_DrivingModeSts_50ms
#define Ra_Transmit_CtApPathPlanner_PpSysManager_DrivingModeSts_50ms Ra_Transmit_CtApSysManager_PpSysManager_DrivingModeSts_50ms
#define Ra_Transmit_CtApPrediction_PpSysManager_DrivingModeSts_50ms Ra_Transmit_CtApSysManager_PpSysManager_DrivingModeSts_50ms
#define Ra_Transmit_CtApStateMonitor_PpSysManager_DrivingModeSts_50ms Ra_Transmit_CtApSysManager_PpSysManager_DrivingModeSts_50ms
#define Ra_Transmit_CtApTrafficElementFusion_PpSysManager_DrivingModeSts_50ms Ra_Transmit_CtApSysManager_PpSysManager_DrivingModeSts_50ms
#define Ra_Transmit_CtApTransformer_PpSysManager_DrivingModeSts_50ms Ra_Transmit_CtApSysManager_PpSysManager_DrivingModeSts_50ms
#define Ra_Transmit_CtApUSBCom_PpSysManager_DrivingModeSts_50ms Ra_Transmit_CtApSysManager_PpSysManager_DrivingModeSts_50ms
void Ra_Transmit_CtApSysManager_PpSysManager_DrivingModeSts_50ms (Dt_RECORD_DrivingModeSts * tDeDrivingModeSts);
  
#define Ra_Transmit_CtApPer_PH00_PpPdUSBComRead Ra_Transmit_CtApUSBCom_PpPdUSBComWrite
#define Ra_Transmit_CtApUSBCom_PpPdUSBComRead Ra_Transmit_CtApUSBCom_PpPdUSBComWrite
void Ra_Transmit_CtApUSBCom_PpPdUSBComWrite (Dt_RECORD_USBCom_Critical * tDeUSBCom_Critical);
  
#define Ra_Transmit_CtApSysManager_PpUSBCom_CtApSysManager_100ms Ra_Transmit_CtApUSBCom_PpUSBCom_CtApSysManager_100ms
void Ra_Transmit_CtApUSBCom_PpUSBCom_CtApSysManager_100ms (Dt_RECORD_FICM2IECUSpdCtrl * tDeFICM2IECUSpdCtrl);
  
#define Ra_Transmit_CtApInteractionProcess_PpUSBCom_InteractionProcess_100ms Ra_Transmit_CtApUSBCom_PpUSBCom_InteractionProcess_100ms
void Ra_Transmit_CtApUSBCom_PpUSBCom_InteractionProcess_100ms (Dt_RECORD_ParkingSpaceDspFeedBack * tDeParkingSpaceDspFeedBack);
  
#define Ra_Transmit_CtApApa_FreeRunning_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApBISTASIL_PH00_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApBISTASIL_SH00_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApBISTQM_PH00_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApBISTQM_SH00_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApComASILB_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApComASILD_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApComQM_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApDR_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApDSC_PH00_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApDSC_SH00_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApDiagnosticManager_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApE2ETranASILB_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApE2ETranASILD_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApFreeSpaceFusion_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApHighFrequencyPositioning_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApHostSupervisionMaster_SH00_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApHostSupervisionSlave_PH00_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApImageProcess_FreeRunning_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApInertialProcess_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApIntegratedPositioning_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApInteractionProcess_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApLaneFusion_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApLocBuffer_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApMeProcess_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApMiddleMapmatching_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApMiddlewareASIL_PH00_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApMiddlewareASIL_SH00_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApMirrorDataManager_FreeRunning_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApMwrProcess_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApObstacleFusion_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApParkingLot_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApPathPlanner_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApPer_PH00_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApPer_SH00_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApPrediction_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApSOMEIPGW_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApStateMonitor_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApStbMASIL_PH00_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApStbMASIL_SH00_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApSysManager_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApTrafficElementFusion_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApTransformer_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApUSBCom_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtApUltrasonicHandler_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtCdDebug_PH00_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtCdDebug_SH00_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtCdErrorHandlerMaster_SH00_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtCdErrorHandlerProxy_PH00_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtCdEyeQCom_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtCdLCSS_PH00_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtCdTimeMonitor_PH00_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
#define Ra_Transmit_CtCdTimeMonitor_SH00_PpPFProvidedData Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
void Ra_Transmit_CtCdLCSM_SH00_PpPFProvidedData
    ( Dt_IFSET_VERSION * tDeIFSETVersion
    , Dt_ENUM_LCS_State * tDeLCSPH00State
    , Dt_ENUM_LCS_State * tDeLCSSH00State
    , Dt_ENUM_LCS_State * tDeLCSSH01State
    , Dt_ENUM_LCS_State * tDeLCSSystemState
    , Dt_ENUM_VAR_HWVariant * tDeVARHWVariant
    );
  
#define Ra_Transmit_CtApApa_FreeRunning_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApBISTASIL_PH00_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApBISTASIL_SH00_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApBISTQM_PH00_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApBISTQM_SH00_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApComASILB_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApComASILD_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApComQM_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApDR_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApDSC_PH00_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApDSC_SH00_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApDiagnosticManager_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApE2ETranASILB_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApE2ETranASILD_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApFreeSpaceFusion_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApHighFrequencyPositioning_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApHostSupervisionMaster_SH00_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApHostSupervisionSlave_PH00_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApImageProcess_FreeRunning_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApInertialProcess_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApIntegratedPositioning_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApInteractionProcess_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApLaneFusion_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApLocBuffer_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApMeProcess_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApMiddleMapmatching_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApMiddlewareASIL_PH00_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApMiddlewareASIL_SH00_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApMirrorDataManager_FreeRunning_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApMwrProcess_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApObstacleFusion_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApParkingLot_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApPathPlanner_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApPer_PH00_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApPer_SH00_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApPrediction_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApSOMEIPGW_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApStateMonitor_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApStbMASIL_PH00_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApStbMASIL_SH00_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApSysManager_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApTrafficElementFusion_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApTransformer_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApUSBCom_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtApUltrasonicHandler_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtCdDebug_PH00_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtCdDebug_SH00_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtCdErrorHandlerMaster_SH00_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtCdErrorHandlerProxy_PH00_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtCdEyeQCom_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtCdLCSS_PH00_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtCdTimeMonitor_PH00_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
#define Ra_Transmit_CtCdTimeMonitor_SH00_PpPfInformation Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
void Ra_Transmit_CtCdLCSM_SH00_PpPfInformation
    ( Dt_RECORD_StbmTimestamp * tDeBuildDate
    , Dt_BuildRevision * tDeBuildRevision
    , Dt_Record_Version * tDePlatformVersion
    , Dt_ARRAY5_ReleaseType * tDeReleaseType
    , Dt_IFSET_VERSION * tDeSystemVersion
    );
  


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* RA_TRANSMIT_H */
